const fs = require('fs');
const path = require('path');
const {
  processPlace,
  saveCache,
  cachePath,
  auditCsvPath,
  reviewCsvPath,
  generatedDataPath
} = require('./enrichPexelsImages');

console.log('===========================================================');
console.log('STARTING FULL PEXELS DATASET ENRICHMENT (BATCH PROCESSING)');
console.log('===========================================================\n');

// Load generated data
const content = fs.readFileSync(generatedDataPath, 'utf8');

const stateMatch = content.match(/export const generatedStates: State\[\] = (\[[\s\S]*?\]);/);
const cityMatch = content.match(/export const generatedCities: City\[\] = (\[[\s\S]*?\]);/);
const placeMatch = content.match(/export const generatedPlaces: Place\[\] = (\[[\s\S]*?\]);/);

const states = JSON.parse(stateMatch[1]);
const cities = JSON.parse(cityMatch[1]);
const places = JSON.parse(placeMatch[1]);

const stateMap = new Map(states.map(s => [s.id, s]));
const cityMap = new Map(cities.map(c => [c.id, c]));

// Load existing cache
let cache = {};
if (fs.existsSync(cachePath)) {
  try {
    cache = JSON.parse(fs.readFileSync(cachePath, 'utf8'));
  } catch {
    cache = {};
  }
}

const usedPhotoIds = new Set();
Object.values(cache).forEach(item => {
  if (item.pexels_photo_id) usedPhotoIds.add(item.pexels_photo_id);
});

console.log(`Loaded ${places.length} places. Cached: ${Object.keys(cache).length}. Unique photos used: ${usedPhotoIds.size}.\n`);

async function processAll() {
  const BATCH_SIZE = 50;
  let batchCount = 0;
  let replacedExact = 0;
  let replacedRelevant = 0;
  let keptExisting = 0;
  let rateLimitHit = false;

  for (let i = 0; i < places.length; i++) {
    const p = places[i];
    const res = await processPlace(p, cityMap, stateMap, usedPhotoIds);

    if (res.match_type === 'exact') replacedExact++;
    else if (res.match_type === 'relevant') replacedRelevant++;
    else keptExisting++;

    batchCount++;

    if (batchCount % BATCH_SIZE === 0 || i === places.length - 1) {
      console.log(`Progress: [${i + 1}/${places.length}] — Exact: ${replacedExact} | Relevant: ${replacedRelevant} | Kept: ${keptExisting}`);
      saveCache();
    }
  }

  // Update places in generatedData.ts
  places.forEach(p => {
    const cached = cache[p.id];
    if (cached && cached.status === 'replaced' && cached.new_image_url) {
      p.cover_image = cached.new_image_url;
      p.images = [cached.new_image_url];
    }
  });

  // Re-write generatedData.ts
  const updatedCodeContent = `// ═══════════════════════════════════════════════════════════════════════════════
// AUTO-GENERATED by scripts/processFullPexelsDataset.js — DO NOT EDIT MANUALLY
// ${new Date().toISOString()}
// ═══════════════════════════════════════════════════════════════════════════════

import type { State, City, Place } from '../types';

export const generatedStates: State[] = ${JSON.stringify(states, null, 2)};

export const generatedCities: City[] = ${JSON.stringify(cities, null, 2)};

export const generatedPlaces: Place[] = ${JSON.stringify(places, null, 2)};

export const cityTransportInfo: Record<string, { airport?: string; railway?: string; bus?: string }> = {
  "Bengaluru": { airport: "Kempegowda International Airport (BLR)", railway: "KSR Bengaluru City Junction (SBC)", bus: "Majestic Bus Stand (KBS)" },
  "Mumbai": { airport: "Chhatrapati Shivaji Maharaj International Airport (BOM)", railway: "Chhatrapati Shivaji Maharaj Terminus (CSMT)", bus: "Mumbai Central Bus Station" },
  "Delhi": { airport: "Indira Gandhi International Airport (DEL)", railway: "New Delhi Railway Station (NDLS)", bus: "ISBT Kashmiri Gate" },
  "Chennai": { airport: "Chennai International Airport (MAA)", railway: "Chennai Central (MAS)", bus: "CMBT Koyambedu" },
  "Kolkata": { airport: "Netaji Subhash Chandra Bose International Airport (CCU)", railway: "Howrah Junction (HWH)", bus: "Esplanade Bus Station" },
  "Hyderabad": { airport: "Rajiv Gandhi International Airport (HYD)", railway: "Secunderabad Junction (SC)", bus: "MGBS Hyderabad" },
  "Jaipur": { airport: "Jaipur International Airport (JAI)", railway: "Jaipur Junction (JP)", bus: "Sindhi Camp Bus Stand" },
  "Kochi": { airport: "Cochin International Airport (COK)", railway: "Ernakulam Junction (ERS)", bus: "KSRTC Bus Stand Ernakulam" },
  "Visakhapatnam": { airport: "Visakhapatnam International Airport (VTZ)", railway: "Visakhapatnam Junction (VSKP)", bus: "RTC Complex Bus Station" },
  "Ahmedabad": { airport: "Sardar Vallabhbhai Patel International Airport (AMD)", railway: "Ahmedabad Junction (ADI)", bus: "GSRTC Geeta Mandir Bus Station" },
  "Theni": { airport: "Madurai International Airport (IXM - 85 km)", railway: "Theni Railway Station (TNI)", bus: "Theni Central Bus Stand" }
};
`;

  fs.writeFileSync(generatedDataPath, updatedCodeContent, 'utf8');

  // Generate Audit CSV
  const auditHeader = 'place_id,place_name,city,state,old_image_url,new_image_url,pexels_photo_id,pexels_url,photographer,photographer_url,query_used,match_type,match_score,action,status\n';
  const auditLines = Object.values(cache).map(item => {
    return [
      `"${item.place_id}"`,
      `"${(item.place_name || '').replace(/"/g, '""')}"`,
      `"${(item.city || '').replace(/"/g, '""')}"`,
      `"${(item.state || '').replace(/"/g, '""')}"`,
      `"${item.old_image_url}"`,
      `"${item.new_image_url}"`,
      `"${item.pexels_photo_id || ''}"`,
      `"${item.pexels_page_url || ''}"`,
      `"${(item.photographer || '').replace(/"/g, '""')}"`,
      `"${item.photographer_url || ''}"`,
      `"${(item.query_used || '').replace(/"/g, '""')}"`,
      `"${item.match_type}"`,
      item.match_score,
      `"${item.status === 'replaced' ? (item.match_type === 'exact' ? 'REPLACED_EXACT' : 'REPLACED_RELEVANT') : 'KEPT_EXISTING'}"`,
      `"${item.status}"`
    ].join(',');
  });

  fs.writeFileSync(auditCsvPath, auditHeader + auditLines.join('\n'), 'utf8');

  // Generate Needs Review CSV
  const reviewHeader = 'place_id,place_name,city,state,match_score,reason\n';
  const reviewLines = Object.values(cache)
    .filter(item => item.status !== 'replaced' || item.match_score < 60)
    .map(item => [
      `"${item.place_id}"`,
      `"${(item.place_name || '').replace(/"/g, '""')}"`,
      `"${(item.city || '').replace(/"/g, '""')}"`,
      `"${(item.state || '').replace(/"/g, '""')}"`,
      item.match_score,
      `"${item.match_score < 60 ? 'Low confidence score' : 'No photo found'}"`
    ].join(','));

  fs.writeFileSync(reviewCsvPath, reviewHeader + reviewLines.join('\n'), 'utf8');

  console.log('\n===========================================================');
  console.log('FULL PEXELS ENRICHMENT COMPLETE!');
  console.log('===========================================================');
  console.log(`- Total Places: ${places.length}`);
  console.log(`- Pexels Exact Replacements: ${replacedExact}`);
  console.log(`- Pexels Relevant Replacements: ${replacedRelevant}`);
  console.log(`- Existing Images Retained: ${keptExisting}`);
  console.log(`- Unique Pexels Photos Used: ${usedPhotoIds.size}`);
  console.log(`- Audit CSV written to: ${auditCsvPath}`);
  console.log(`- Review CSV written to: ${reviewCsvPath}`);
}

processAll();
